kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-clam
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    matchLabels:
      app: my-clam
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: my-clam
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: my-clam
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: clam-storage
      volumes:
        - name: clam-storage
          persistentVolumeClaim:
            claimName: data-pv-claim
