---
kind: Service
apiVersion: v1
metadata:
  name: my-clam-svc
spec:
  selector:
    app: my-clam
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30080
